spring:

    datasource:
        url: jdbc:mysql://localhost:3306/
        username: root
        password: lldj123414
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect


